INSERT INTO score_tracker (user_id, user_name, score) VALUES ('1', 'Messi'   ,100);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('2', 'Nadal'   ,101);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('3', 'Adi'     ,102);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('4', 'NoName'  ,103);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('5', 'Zelensky',104);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('6', 'Virat'   ,106);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('7', 'Sachin'  ,107);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('8', 'Obama'   ,108);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('9', 'Putin'   ,109);
INSERT INTO score_tracker (user_id, user_name, score) VALUES ('10','Modi'    ,110);
